In [1]:
# SQL Alchemy
import sqlalchemy
from sqlalchemy import create_engine, inspect
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy.engine import reflection

# PyMySQL 
import pymysql
pymysql.install_as_MySQLdb()

# Pandas
import pandas as pd

In [2]:
names_1 = pd.read_excel("bbnames.xlsx", sheet_name=0, header=0, skiprows = None)
names_1.head()

,OTU ID #,Lowest Taxonomic Level of Bacteria/Archaea Found,940,941,943,944,945,946,947,948,...,1563,1564,1572,1573,1574,1576,1577,1581,1601,<-- Belly button sample numbers
0,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
2,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
3,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
4,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN

In [3]:
names_1.columns

Index([                                        'OTU ID #',
       'Lowest Taxonomic Level of Bacteria/Archaea Found',
                                                      940,
                                                      941,
                                                      943,
                                                      944,
                                                      945,
                                                      946,
                                                      947,
                                                      948,
       ...
                                                     1563,
                                                     1564,
                                                     1572,
                                                     1573,
                                                     1574,
                                                     1576,
                                                     1577,
                                                     1581,
                                                     1601,
                        '<-- Belly button sample numbers'],
      dtype='object', length=156)

In [28]:
names_2 = pd.read_excel("bbnames.xlsx", sheet_name=1, header=0, skiprows = None,  )
names_2.head()
names_2 = names_2.transpose()
names_2.reset_index()

,index,0,1,2,3,4,5,6,7,8,...,11,12,13,14,15,16,17,18,19,20
0,Data,Collection event,Ethnicity,Gender (male/female),Age (in years),Washing Frequency (belly button scrubs per week),Innie or Outtie?,City and State in which participant lived at t...,Country in which participant lived from age 0 ...,Zip code in which participant lived from age 0...,...,Do you Currently Live with a Dog (yes or no)?,Do you Currently Live with a Cat (yes or no)?,Impervious surface (such as cement) in center ...,Net Primary Productivity in center of zipcode ...,Mean maximum monthly temperature in center of ...,Percent Forest Cover in center of zipcode wher...,Impervious surface (such as cement) in center ...,Net Primary Productivity Impervious surface (s...,Mean maximum monthly temperaturein center of z...,Percent Forest Cover in center of zipcode wher...
1,940,BellyButtonsScienceOnline,Caucasian,F,24,2,I,Beaufort/NC,usa,22306,...,no,no,8852,37.1722,54.5,NaN,1,NaN,33.99,25.5
2,941,...,Caucasian/Midleastern,F,34,1,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,943,BellyButtonsScienceOnline,Caucasian,F,49,1,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,944,BellyButtonsScienceOnline,European,M,44,1,I,New Haven / CT,usa,7079,...,no,yes,NaN,35.8167,16,NaN,0,6567,32.4033,28.5
5,945,BellyButtonsScienceOnline,Caucasian,F,48,1,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.7833,4,NaN,0,5613,33.6344,24
6,946,BellyButtonsScienceOnline,Caucasian,F,42,3,I,Deerfield/MA,usa,12538,...,no,yes,NaN,34.7611,15.5,NaN,0,6273,29.4033,67.5
7,947,BellyButtonsScienceOnline,Caucasian,M,49,6,I,Chapel Hill/NC,usa,48823,...,no,yes,7491,30.3567,31,NaN,0,5357,30.8811,16.5
8,948,BellyButtonsScienceOnline,Caucasian,M,20,NaN,I,Chapel Hill/NC,usa,27613,...,no,no,NaN,53.8878,0,NaN,31,NaN,31.73,22.5
9,949,BellyButtonsScienceOnline,Caucasian,F,51,3,I,Durham/NC,usa,7009,...,no,no,NaN,35.5344,36,NaN,5,NaN,35.5344,36
10,950,BellyButtonsScienceOnline,Caucasian,M,51,5,I,New York/NY,usa,1730,...,yes,no,6273,29.4033,67.5,NaN,0,NaN,30.4811,33
11,952,BellyButtonsScienceOnline,Caucasian,F,51,7,I,Seattle/ WA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,953,BellyButtonsScienceOnline,Caucasian,F,38,2,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,954,BellyButtonsScienceOnline,Caucasian,M,26,7,I,New York/NY,usa,45429,...,NaN,NaN,6919,34.0078,34.5,NaN,21,6074,34.2633,14.5
14,955,BellyButtonsScienceOnline,Caucasian,F,27,7,I,New York/NY,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,956,BellyButtonsScienceOnline,Caucasian,M,16,7,I,Jacksonville/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,958,BellyButtonsScienceOnline,Caucasian,M,43,5,I,Wilmington/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,959,BellyButtonsScienceOnline,Caucasian,M,40,5,I,Carrboro/NC,usa,93605,...,no,no,7431,30.5833,61.5,NaN,1,4066,38.1456,1.5
18,960,BellyButtonsScienceOnline,Caucasian,M,48,7,I,Lexington/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,961,BellyButtonsScienceOnline,Caucasian,F,35,4,i,"Edmonton, AB",canada,K7V3Z4,...,yes,no,6962,33.8056,15,NaN,'NA',5104,29.5767,22
20,962,BellyButtonsScienceOnline,Caucasian,F,56,1,i,"Washington, DC",usa,60514,...,no,no,7281,29.9544,37.5,NaN,23,NaN,37.2078,18
21,963,BellyButtonsScienceOnline,Caucasian,F,33,3.5,I,Ithaca/ NY,usa,45238,...,no,no,5363,32.65,48.5,NaN,4,6420,33.3367,18.5
22,964,BellyButtonsScienceOnline,Caucasian,F,43,7,I,UK/London,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,966,BellyButtonsScienceOnline,Caucasian,M,56,0,I,Needham/MA,usa,7924,...,no,no,4016,33.2744,64,NaN,6,6762,31.6922,65
24,967,BellyButtonsScienceOnline,Caucasian/Jewish,F,43,1,I,Chapel Hill/NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,968,BellyButtonsScienceOnline,Caucasian,F,38,6,I,St. Louis/MI,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,969,BellyButtonsScienceOnline,Caucasian/Asian,F,31,7,I,Chevy Chase/MD,usa,7071,...,no,no,NaN,30.4811,33,NaN,0,NaN,35.7789,27
27,970,BellyButtonsScienceOnline,Caucasian,F,42,0,i,San Diego/CA,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,971,BellyButtonsScienceOnline,Asian (South),M,36,1,I,Santa Barbara/CA,usa,10533,...,no,no,NaN,37.2078,18,NaN,70,5961,30.5567,23.5
29,972,BellyButtonsScienceOnline,Caucasian,F,31,7,I,Charlotte/NC,usa,55987,...,yes,no,NaN,NaN,9,NaN,0,4949,29.6122,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,1541,BellyButtonsWildLives,Caucasian,F,26,0,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
126,1542,BellyButtonsWildLives,Caucasian,M,36,NaN,I,NC,usa,37343 and 37221,...,no,no,NaN,34.9856,27,NaN,'NA',4826,29.4389,6.5
127,1543,BellyButtonsWildLives,Caucasian,F,34,3,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,1544,BellyButtonsWildLives,Caucasian,F,33,1,I,NC,usa,80106,...,yes,no,4464,33.8011,1,NaN,0,2521,42.2478,2
129,1545,BellyButtonsWildLives,Caucasian,F,39,7,I,NC,usa,92054,...,no,no,5647,29.8633,34,NaN,0,5744,32.5411,15
130,1546,BellyButtonsWildLives,Caucasian,M,34,3,I,NC,usa,13104,...,yes,no,NaN,35.7789,27,NaN,0,7281,29.9544,37.5
131,1547,BellyButtonsWildLives,NaN,M,38,0,I,NC,usa,92014,...,no,no,7817,29.6967,17.5,NaN,36,NaN,36.6122,10
132,1548,BellyButtonsWildLives,Caucasian,M,6,0,I,NC,usa,27607,...,yes,no,NaN,35.5344,26,NaN,NaN,NaN,NaN,NaN
133,1549,BellyButtonsWildLives,Caucasian,F,37,3,I,NC,usa,28655,...,yes,no,6940,31.6811,51.5,NaN,63,NaN,35.5322,7.5
134,1550,BellyButtonsWildLives,Caucasian,F,29,7,I,NC,usa,55127,...,no,no,2521,42.2478,2,NaN,0,NaN,33.1922,NaN
135,1551,BellyButtonsWildLives,Caucasian,M,26,0,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,1552,BellyButtonsWildLives,Caucasian,M,25,3,I,NC,usa,63301,...,no,no,NaN,36.6122,10,NaN,0,4464,33.8011,1
137,1553,BellyButtonsWildLives,Caucasian,F,50,0,I,NC,usa,70808,...,yes,no,NaN,33.1922,NaN,NaN,11,NaN,37.7833,4
138,1554,BellyButtonsWildLives,Caucasian,F,18,0,I,NC,usa,27607,...,yes,no,6115,29.7944,31.5,NaN,70,NaN,34.5411,11
139,1555,BellyButtonsWildLives,Caucasian,M,26,0,I,NC,usa,8057,...,yes,yes,5104,29.5767,22,NaN,42,NaN,36.4767,32
140,1556,BellyButtonsWildLives,Hispanic,M,34,0,I,NC,colombia,NaN,...,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,1557,BellyButtonsWildLives,Caucasian,F,26,2,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,1558,BellyButtonsWildLives,Caucasian,M,26,1,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,1561,BellyButtonsWildLives,Caucasian,M,31,2,I,NC,usa,28515,...,no,yes,NaN,34.7833,8.5,NaN,0,7817,29.6967,17.5
144,1562,BellyButtonsWildLives,Caucasian,M,39,0,I,MT,usa,48640,...,yes,no,5081,43.4589,4.5,NaN,0,6450,30.3722,25
145,1563,BellyButtonsWildLives,Caucasian,F,31,0,I,MT,usa,36207,...,yes,no,NaN,24.2011,9.5,NaN,0,7431,30.5833,61.5
146,1564,BellyButtonsWildLives,Caucasian,F,36,5,I,NC,usa,27530,...,no,yes,5875,34.8789,43.5,NaN,0,6843,34.3411,10
147,1572,BellyButtonsWildLives,Caucasian,F,33,0,I,NC,Peru,Lima,...,no,no,NaN,37.2233,14.5,NaN,'NA',NaN,NaN,NaN
148,1573,BellyButtonsWildLives,Caucasian,M,53,0,I,NC,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149,1574,BellyButtonsWildLives,Caucasian,M,30,7,I,OK,usa,66210,...,no,no,7131,29.1478,40.5,NaN,3,NaN,39.6767,9.5
150,1576,BellyButtonsWildLives,Caucasian,F,33,0,I,NC,usa,21045,...,no,yes,NaN,35.7611,13.5,NaN,12,NaN,32.7189,34.5
151,1577,BellyButtonsWildLives,Caucasian,M,26,0,I,NC,usa,21228,...,no,yes,893,40.2233,0,NaN,23,NaN,36.27,27
152,1581,BellyButtonsWildLives,Asian (American),F,22,2,I,NC,usa,28056,...,no,no,5026,30.0011,25.5,NaN,0,6962,33.8056,15
153,1601,BellyButtonsWildLives,Caucasian,F,22,2,I,NC,usa,29615,...,yes,no,NaN,NaN,NaN,NaN,1,NaN,32.89,45.5
154,<-- Belly button sample numbers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
names_3 = pd.read_excel('bbnames.xlsx', sheet_name=2, header = 0, skiprows=None)
names_3.head()

                                             Sheet 1
0  Belly Button Data Matrix: Belly button sample ...
1                                            Sheet 2
2  Belly Button Meta Data Matrix: Again, belly bu...

In [6]:
otu_1 = pd.read_excel("bbotu.xlsx", sheet_name=0, header=0, skiprows = None)
otu_1.head()

,Kingdom/Domain,Phylum,Class,Order,Family,Genus,Family_Genus,1153,1161,1169,...,YWL1043,CALS1006,CALS1014,CALS1023,YWL1018,YWL1085,YWL1209,YWL1103,YWL1076,YWL1197
0,Unclassified,Other,Other,Other,Other,Other,NaN,0,0,0,...,0,0,0.002,0,0,0,0,0.005,0,0
1,k__Archaea,p__Crenarchaeota,c__Thaumarchaeota,o__Cenarchaeales,f__Cenarchaeaceae,g__,f__Cenarchaeaceae g__,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,k__Archaea,p__Crenarchaeota,c__Thaumarchaeota,o__Nitrososphaerales,f__Nitrososphaeraceae,g__Candidatus Nitrososphaera,f__Nitrososphaeraceae g__Candidatus Nitrososph...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,k__Archaea,p__Euryarchaeota,c__Methanobacteria,o__Methanobacteriales,f__Methanobacteriaceae,g__Methanobacterium,f__Methanobacteriaceae g__Methanobacterium,0,0,0,...,0,0,0,0,0,0,0,0.002,0,0
4,k__Archaea,p__Euryarchaeota,c__Methanobacteria,o__Methanobacteriales,f__Methanobacteriaceae,g__Methanobrevibacter,f__Methanobacteriaceae g__Methanobrevibacter,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
otu_1.head()

,Kingdom/Domain,Phylum,Class,Order,Family,Genus,Family_Genus,1153,1161,1169,...,YWL1043,CALS1006,CALS1014,CALS1023,YWL1018,YWL1085,YWL1209,YWL1103,YWL1076,YWL1197
0,Unclassified,Other,Other,Other,Other,Other,NaN,0,0,0,...,0,0,0.002,0,0,0,0,0.005,0,0
1,k__Archaea,p__Crenarchaeota,c__Thaumarchaeota,o__Cenarchaeales,f__Cenarchaeaceae,g__,f__Cenarchaeaceae g__,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,k__Archaea,p__Crenarchaeota,c__Thaumarchaeota,o__Nitrososphaerales,f__Nitrososphaeraceae,g__Candidatus Nitrososphaera,f__Nitrososphaeraceae g__Candidatus Nitrososph...,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,k__Archaea,p__Euryarchaeota,c__Methanobacteria,o__Methanobacteriales,f__Methanobacteriaceae,g__Methanobacterium,f__Methanobacteriaceae g__Methanobacterium,0,0,0,...,0,0,0,0,0,0,0,0.002,0,0
4,k__Archaea,p__Euryarchaeota,c__Methanobacteria,o__Methanobacteriales,f__Methanobacteriaceae,g__Methanobrevibacter,f__Methanobacteriaceae g__Methanobrevibacter,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
otu_2 = pd.read_excel("bbotu.xlsx", sheet_name=1, header=0, skiprows = None)
otu_2.head()

,ID,Ethnicity_Catagory,Ethnicity_Quest,Gender,Age,Age_Range,Wash_Freq of BB (# times per week),Wash_Range,Innie_or_outie,Country til age 12,ZIP code til age 12,Country ages 13-19,Zipcode ages 13-19,Current ZIPcode,Current City,Current State,Reads
0,1153,non-Hispanic White,Caucasian,Female,18,8 to 18,Unknown,Unknown,Innie,Unknown,Unknown,Unknown,Unknown,Unknown,Raleigh,NC,1000
1,1161,non-Hispanic White,Caucasian,Male,28,19 to 35,Unknown,Unknown,Innie,Unknown,Unknown,Unknown,Unknown,Unknown,Raleigh,NC,1000
2,1169,Indian,Indian,Male,7,0 to 7,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,FairFax,VA,1000
3,979,Unknown,Unknown,Female,35,19 to 35,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Durham,NC,1000
4,1113,non-Hispanic Black,African American,Female,8,8 to 18,Unknown,Unknown,Innie,Unknown,Unknown,Unknown,Unknown,Unknown,Conway,NC,1000

In [9]:
otu_3 = pd.read_excel("bbotu.xlsx", sheet_name=2, header=0, skiprows = None)
otu_3.head()

                                             Sheet 1
0  Belly Button Data Matrix: Belly button sample ...
1                                            Sheet 2
2  Belly Button Meta Data Matrix: Belly button sa...

In [10]:
otu_descrip = names_1['Lowest Taxonomic Level of Bacteria/Archaea Found']

In [11]:
otu_descrip = list(otu_descrip)
otu_descrip

['Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus',
 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Halococcus',
 'Archaea;Euryarchaeota;Halobacteria;Halobacteriales;Halobacteriaceae;Natronorubrum',
 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
 'Archaea;Euryarchaeota;Methanobacteria;Methanobacteriales;Methanobacteriaceae;Methanobrevibacter',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria',
 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 'Bacteria;Acidobacteria;Acidobacteria_Gp1;Gp1',
 'Bacteria;Acidobacteria;Acidobacteria_Gp10;Gp10',
 'Bacteria;Acidobacteria;Acidobacteria_Gp16;Gp16',
 'Bacteria;Acidobacteria;Acidobacteria_Gp16;Gp16',
 'Bacteria;Acidobacteria;Acidobacteria_Gp16;Gp16',
 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 'Bacteria;Acidobacteria;Acidobacteria_Gp2;Gp2',
 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 'Bacteria;Acidobacteria;Acidobacteria_Gp3;Gp3',
 'Bacteria;Acidobacteria;Acidobacteria_Gp4;Gp4',
 'Bacteria;Acidobacteria;Acidobacteria_Gp4;Gp4',
 'Bacteria;Acidobacteria;Acidobacteria_Gp6;Gp6',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria',
 'Bacteria;Actinobacteria;Actinobacteria;Acidimicrobiales',
 'Bacteria;Actinobacteria;Actinobacteria;Acidimicrobiales;Iamiaceae;Iamia',
 'Bacteria;Actinobacteria;Actinobacteria;Acidimicrobidae_incertae_sedis;Ilumatobacter',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',
 'Bacteria;Actinobacteria;Actinobacteria;Actinomycetales',

In [ ]:
trans = names_1.transpose()
df = trans[0][2:]
otu_id = list(df.index[:-1])
otu_id
otu_id_list = ["BB_" + str(s) for s in otu_id]

otu_id_list

In [54]:
sample_data = pd.read_csv('Belly_Button_Biodiversity_Metadata.csv')
sample_data.head()

,SAMPLEID,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.783333,4.0,NaN,0,5613.0,33.634445,24.0

In [61]:
sample_id = input('what id do you want?')
sample_return = sample_data.loc[sample_data['SAMPLEID'] == int(sample_id)]

sample_return

what id do you want?940

,SAMPLEID,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5

In [60]:
sample_data.dtypes

SAMPLEID            int64
EVENT              object
ETHNICITY          object
GENDER             object
AGE               float64
WFREQ             float64
BBTYPE             object
LOCATION           object
COUNTRY012         object
ZIP012             object
COUNTRY1319        object
ZIP1319            object
DOG                object
CAT                object
IMPSURFACE013     float64
NPP013            float64
MMAXTEMP013       float64
PFC013            float64
IMPSURFACE1319     object
NPP1319           float64
MMAXTEMP1319      float64
PFC1319           float64
dtype: object

In [62]:
# names_2

In [83]:
sample_data = pd.read_csv('Belly_Button_Biodiversity_Metadata.csv')
sample_return = sample_data.loc[sample_data['SAMPLEID'] == int(sample_id)]
sample_return['WFREQ'].to_json()

'{"0":2.0}'

AttributeError: 'str' object has no attribute 'values'

In [ ]:
sample_data = pd.read_csv('bello_button_biodiversity_samples.csv')
sample_return = sample_data.loc[sample_data['SAMPLEID'] == int(sample_id)]
sample_return['WFREQ'].to_json()